<%@page pageEncoding="UTF-8" isELIgnored="false" session="false"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%><%@taglib prefix="f" uri="http://www.slim3.org/functions"%><%@ page import="jp.co.dol.common.*" %><?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>
	<channel>
		<title>障害一覧</title>
		<atom:link href="http://andante.in/i/feed/" rel="self" type="application/rss+xml" />
		<link>http://andante.in/i</link>
		<description></description>
		<lastBuildDate></lastBuildDate>
		<language>ja</language>
		<sy:updatePeriod>hourly</sy:updatePeriod>
		<sy:updateFrequency>1</sy:updateFrequency>
		<generator>http://sys-dolphin.appspot.com/failure/xml</generator>
<c:forEach var="head" items="${failureList}" varStatus="hs" >
		<item>
			<pjno>${f:h(head.pjNo)}</pjno>
			<pjname>${f:h(head.pjNo)}</pjname>
			<no>${f:h(head.no)}</no>
			<postdate>${f:h(head.postDate)}</postdate>
			<title>${f:h(head.title)}</title>
			<supportkbn>${f:h(head.supportKbn)}</supportkbn>
			<prioritylv>${f:h(head.priorityLv)}</prioritylv>
			<importantlv>${f:h(head.importantLv)}</importantlv>
			<startdate>${f:h(head.startDate)}</startdate>
			<enddate>${f:h(head.endDate)}</enddate>
			<releasedate>${f:h(head.releaseDate)}</releasedate>
			<discoveryemp>${f:h(head.discoveryEmp)}</discoveryemp>
			<supportemp>${f:h(head.supportEmp)}</supportemp>
			<troublespots>${f:h(head.troubleSpots)}</troublespots>
			<failurebody>${f:h(head.failureBody)}</failurebody>
			<troublecause>${f:h(head.troubleCause)}</troublecause>
			<troublecausekbn>${f:h(head.troubleCauseKbn)}</troublecausekbn>
			<repairbody>${f:h(head.repairBody)}</repairbody>
			<results>${f:h(head.results)}</results>
			<repairsrc>${f:h(head.repairSrc)}</repairsrc>
			<remarks>${f:h(head.remarks)}</remarks>
			<browser>${f:h(head.browser)}</browser>
		</item>
</c:forEach>
	</channel>
</rss>

<!-- Dynamic page generated in 0.307 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2011-09-26 13:40:43 -->
